// Shalom Fish — Kerala seafood catalogue (ALL DATA)
// Prices in INR. Replace /public/products/*.jpg with real photos (same filenames) to go live.

export const products = [
  {
    id: "seer",
    name: "Seer Fish",
    local: "Neymeen · King Fish",
    category: "Premium Catch",
    price: 899,
    oldPrice: 1099,
    unit: "500 g",
    rating: 4.9,
    reviews: 214,
    image: "/products/seer.jpg",
    premium: true,
    todaysCatch: true,
  },
  {
    id: "karimeen",
    name: "Pearl Spot",
    local: "Karimeen",
    category: "Backwater Special",
    price: 1199,
    oldPrice: 1399,
    unit: "500 g",
    rating: 4.9,
    reviews: 176,
    image: "/products/karimeen.jpg",
    premium: true,
    todaysCatch: true,
  },
  {
    id: "prawns",
    name: "Tiger Prawns",
    local: "Kera Chemmeen",
    category: "Shellfish",
    price: 599,
    oldPrice: 749,
    unit: "500 g",
    rating: 4.8,
    reviews: 302,
    image: "/products/prawns.jpg",
    premium: true,
    todaysCatch: true,
  },
  {
    id: "pomfret",
    name: "Silver Pomfret",
    local: "Aavoli",
    category: "Premium Catch",
    price: 749,
    oldPrice: 899,
    unit: "500 g",
    rating: 4.7,
    reviews: 158,
    image: "/products/pomfret.jpg",
    premium: true,
    todaysCatch: false,
  },
  {
    id: "snapper",
    name: "Red Snapper",
    local: "Chempalli",
    category: "Premium Catch",
    price: 649,
    oldPrice: 799,
    unit: "500 g",
    rating: 4.6,
    reviews: 121,
    image: "/products/snapper.jpg",
    premium: false,
    todaysCatch: true,
  },
  {
    id: "kingfish",
    name: "Kingfish Steaks",
    local: "Neymeen Cut",
    category: "Ready to Cook",
    price: 949,
    oldPrice: 1149,
    unit: "500 g",
    rating: 4.8,
    reviews: 198,
    image: "/products/kingfish.jpg",
    premium: true,
    todaysCatch: false,
  },
  {
    id: "squid",
    name: "Squid",
    local: "Koonthal · Kanava",
    category: "Shellfish",
    price: 399,
    oldPrice: 499,
    unit: "500 g",
    rating: 4.5,
    reviews: 143,
    image: "/products/squid.jpg",
    premium: false,
    todaysCatch: true,
  },
  {
    id: "crab",
    name: "Mud Crab",
    local: "Njandu",
    category: "Shellfish",
    price: 549,
    oldPrice: 699,
    unit: "500 g",
    rating: 4.6,
    reviews: 96,
    image: "/products/crab.jpg",
    premium: true,
    todaysCatch: false,
  },
  {
    id: "mackerel",
    name: "Indian Mackerel",
    local: "Ayla",
    category: "Everyday",
    price: 199,
    oldPrice: 249,
    unit: "500 g",
    rating: 4.4,
    reviews: 264,
    image: "/products/mackerel.jpg",
    premium: false,
    todaysCatch: true,
  },
  {
    id: "sardine",
    name: "Sardine",
    local: "Mathi · Chaala",
    category: "Everyday",
    price: 149,
    oldPrice: 199,
    unit: "500 g",
    rating: 4.5,
    reviews: 341,
    image: "/products/sardine.jpg",
    premium: false,
    todaysCatch: true,
  },
  {
    id: "tuna",
    name: "Tuna",
    local: "Choora",
    category: "Everyday",
    price: 349,
    oldPrice: 429,
    unit: "500 g",
    rating: 4.5,
    reviews: 132,
    image: "/products/tuna.jpg",
    premium: false,
    todaysCatch: false,
  },
  {
    id: "anchovy",
    name: "Anchovy",
    local: "Netholi · Kozhuva",
    category: "Everyday",
    price: 179,
    oldPrice: 229,
    unit: "500 g",
    rating: 4.6,
    reviews: 187,
    image: "/products/anchovy.jpg",
    premium: false,
    todaysCatch: false,
  },
];

export const discountPct = (p) =>
  p.oldPrice ? Math.round(((p.oldPrice - p.price) / p.oldPrice) * 100) : 0;

export const categories = [
  { id: "premium", label: "Premium Catch", icon: "★" },
  { id: "backwater", label: "Backwater", icon: "≈" },
  { id: "shellfish", label: "Shellfish", icon: "◆" },
  { id: "ready", label: "Ready to Cook", icon: "✦" },
  { id: "everyday", label: "Everyday", icon: "●" },
  { id: "dried", label: "Dried Fish", icon: "❈" },
];
