// Shalom Fish — Kerala seafood catalogue.
//
// 20 fish in demand order (1 = sells most). Categories follow the fish's actual
// habitat, which is how Kerala buyers think about them.
//
// ⚠️ PRICES ARE ESTIMATES. They're typical Kochi retail rates per 500 g and will
// be wrong for your shop on any given day — seafood pricing moves with the
// landing. Set your real rates in Admin → Inventory before going live.
//
// ⚠️ IMAGES: every fish points at /products/<id>.jpg. Drop a photo with that
// exact filename into public/products/, or upload one per product in
// Admin → Add/Edit Product.
//
// `hidden: true` keeps a fish off the storefront entirely — use it for anything
// you don't have in today, or anything still missing a photo and a real price.

export const products = [
  {
    id: "mathi",
    name: "Sardine",
    local: "Mathi · Chaala",
    category: "Marine",
    price: 90,
    oldPrice: 110,
    unit: "500 g",
    rating: 4.8,
    reviews: 312,
    image: "/products/mathi.jpg",
    todaysCatch: true,
  },
  {
    id: "ayala",
    name: "Indian Mackerel",
    local: "Ayala",
    category: "Marine",
    price: 140,
    oldPrice: 170,
    unit: "500 g",
    rating: 4.8,
    reviews: 286,
    image: "/products/ayala.jpg",
    todaysCatch: true,
  },
  {
    id: "choora",
    name: "Tuna",
    local: "Choora",
    category: "Marine",
    price: 180,
    oldPrice: 210,
    unit: "500 g",
    rating: 4.7,
    reviews: 198,
    image: "/products/choora.jpg",
  },
  {
    id: "neymeen",
    name: "Seer Fish",
    local: "Neymeen · Ayakoora",
    category: "Marine",
    price: 550,
    oldPrice: 650,
    unit: "500 g",
    rating: 4.9,
    reviews: 241,
    image: "/products/neymeen.jpg",
    premium: true,
    todaysCatch: true,
  },
  {
    id: "natholi",
    name: "Anchovy",
    local: "Natholi · Kozhuva",
    category: "Marine",
    price: 100,
    oldPrice: 120,
    unit: "500 g",
    rating: 4.6,
    reviews: 154,
    image: "/products/natholi.jpg",
  },
  {
    id: "karimeen",
    name: "Pearl Spot",
    local: "Karimeen",
    category: "Brackish",
    price: 450,
    oldPrice: 540,
    unit: "500 g",
    rating: 4.9,
    reviews: 203,
    image: "/products/karimeen.jpg",
    premium: true,
  },
  {
    id: "avoli",
    name: "Pomfret",
    local: "Avoli",
    category: "Marine",
    price: 420,
    oldPrice: 500,
    unit: "500 g",
    rating: 4.8,
    reviews: 167,
    image: "/products/avoli.jpg",
    premium: true,
  },
  {
    id: "chemballi",
    name: "Red Snapper",
    local: "Chemballi",
    category: "Marine",
    price: 320,
    oldPrice: 380,
    unit: "500 g",
    rating: 4.7,
    reviews: 142,
    image: "/products/chemballi.jpg",
  },
  {
    id: "koduva",
    name: "Asian Seabass",
    local: "Koduva · Barramundi",
    category: "Brackish",
    price: 340,
    oldPrice: 400,
    unit: "500 g",
    rating: 4.7,
    reviews: 118,
    image: "/products/koduva.jpg",
  },
  {
    id: "kanambu",
    name: "Grey Mullet",
    local: "Kanambu",
    category: "Marine",
    price: 210,
    oldPrice: 250,
    unit: "500 g",
    rating: 4.5,
    reviews: 96,
    image: "/products/kanambu.jpg",
  },
  {
    id: "varaal",
    name: "Snakehead Murrel",
    local: "Varaal",
    category: "Freshwater",
    price: 380,
    oldPrice: 440,
    unit: "500 g",
    rating: 4.7,
    reviews: 88,
    image: "/products/varaal.jpg",
  },
  {
    id: "tilapia",
    name: "Tilapia",
    local: "Tilapia",
    category: "Freshwater",
    price: 130,
    oldPrice: 160,
    unit: "500 g",
    rating: 4.4,
    reviews: 74,
    image: "/products/tilapia.jpg",
  },
  {
    id: "vaala",
    name: "Ribbonfish",
    local: "Vaala",
    category: "Marine",
    price: 190,
    oldPrice: 230,
    unit: "500 g",
    rating: 4.5,
    reviews: 81,
    image: "/products/vaala.jpg",
  },
  {
    id: "sheelavu",
    name: "Barracuda",
    local: "Sheelavu",
    category: "Marine",
    price: 260,
    oldPrice: 310,
    unit: "500 g",
    rating: 4.5,
    reviews: 69,
    image: "/products/sheelavu.jpg",
  },
  {
    id: "vatta",
    name: "Trevally",
    local: "Vatta · Para",
    category: "Marine",
    price: 200,
    oldPrice: 240,
    unit: "500 g",
    rating: 4.4,
    reviews: 63,
    image: "/products/vatta.jpg",
  },
  {
    id: "vila",
    name: "Emperor Fish",
    local: "Vila",
    category: "Marine",
    price: 290,
    oldPrice: 340,
    unit: "500 g",
    rating: 4.5,
    reviews: 52,
    image: "/products/vila.jpg",
  },
  {
    id: "kora",
    name: "Croaker",
    local: "Kora",
    category: "Marine",
    price: 230,
    oldPrice: 270,
    unit: "500 g",
    rating: 4.4,
    reviews: 47,
    image: "/products/kora.jpg",
  },
  {
    id: "motha",
    name: "Cobia",
    local: "Motha",
    category: "Marine",
    price: 360,
    oldPrice: 420,
    unit: "500 g",
    rating: 4.6,
    reviews: 41,
    image: "/products/motha.jpg",
  },
  {
    id: "thirutha",
    name: "Grey Mullet",
    local: "Thirutha",
    category: "Brackish",
    price: 220,
    oldPrice: 260,
    unit: "500 g",
    rating: 4.4,
    reviews: 38,
    image: "/products/thirutha.jpg",
  },
  {
    // Shark is landed far less than it once was, and several species are
    // protected. Ships HIDDEN — turn it on only if you actually stock it and
    // it's legal to sell locally.
    id: "sravu",
    name: "Shark",
    local: "Sravu",
    category: "Marine",
    price: 280,
    oldPrice: 330,
    unit: "500 g",
    rating: 4.2,
    reviews: 24,
    image: "/products/sravu.jpg",
    hidden: true,
  },
];

export const discountPct = (p) =>
  p.oldPrice ? Math.round(((p.oldPrice - p.price) / p.oldPrice) * 100) : 0;

/** A product shows on the storefront unless it is explicitly hidden. */
export const isVisible = (p) => !p.hidden;

export const categories = [
  { id: "marine", label: "Marine", icon: "≋" },
  { id: "brackish", label: "Brackish", icon: "≈" },
  { id: "freshwater", label: "Freshwater", icon: "◦" },
];
